# Minimal Docker-based test environment
FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv sudo curl git bats whiptail bc jq iproute2 kmod nano
ENV TERM=xterm
RUN pip3 install --break-system-packages requests tqdm python-dotenv console-menu pytest pyyaml 
WORKDIR /ethpillar
CMD ["/bin/bash"]
